### ISSUE TITLE
When to release code

### ISSUE THREAD

**Issue by c7w** [JianxGao/C2F-Seg#2]
Hi, thanks for your nice piece of work. I wonder when to release code bcz it has been a while since the conference has ended.

B. R.,
Huan-ang Gao
Tsinghua University

**Comment by JianxGao** [comment]
I will try my best to release it In this week.

**Comment by JianxGao** [comment]
Hi, @c7w:
I have prepared the code and submitted an open-source request to Amazon. Sorry for the inconvenience; it will take at least two weeks. I will release it upon completion of the review.

**Comment by JianxGao** [comment]
Code is released at: https://github.com/amazon-science/c2f-seg.
